[package]
authors = ["Wez Furlong <wez@wezfurlong.org>"]
name = "freetype"
version = "0.1.0"
edition = "2018"
links = "freetype"
build = "build.rs"
publish = false

[dependencies]
fixed.workspace = true

[build-dependencies]
cc.workspace = true
libz-sys = "1.1.22"
pkg-config = "0.3"
